/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TechnologyRouteImport } from './routes/technology'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as OrderRouteImport } from './routes/order'
import { Route as MobileAppRouteImport } from './routes/mobile-app'
import { Route as IndustriesRouteImport } from './routes/industries'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AtfRouteImport } from './routes/atf'
import { Route as IndexRouteImport } from './routes/index'

const TechnologyRoute = TechnologyRouteImport.update({
  id: '/technology',
  path: '/technology',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderRoute = OrderRouteImport.update({
  id: '/order',
  path: '/order',
  getParentRoute: () => rootRouteImport,
} as any)
const MobileAppRoute = MobileAppRouteImport.update({
  id: '/mobile-app',
  path: '/mobile-app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesRoute = IndustriesRouteImport.update({
  id: '/industries',
  path: '/industries',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AtfRoute = AtfRouteImport.update({
  id: '/atf',
  path: '/atf',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/atf': typeof AtfRoute
  '/contact': typeof ContactRoute
  '/industries': typeof IndustriesRoute
  '/mobile-app': typeof MobileAppRoute
  '/order': typeof OrderRoute
  '/services': typeof ServicesRoute
  '/technology': typeof TechnologyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/atf': typeof AtfRoute
  '/contact': typeof ContactRoute
  '/industries': typeof IndustriesRoute
  '/mobile-app': typeof MobileAppRoute
  '/order': typeof OrderRoute
  '/services': typeof ServicesRoute
  '/technology': typeof TechnologyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/atf': typeof AtfRoute
  '/contact': typeof ContactRoute
  '/industries': typeof IndustriesRoute
  '/mobile-app': typeof MobileAppRoute
  '/order': typeof OrderRoute
  '/services': typeof ServicesRoute
  '/technology': typeof TechnologyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/atf'
    | '/contact'
    | '/industries'
    | '/mobile-app'
    | '/order'
    | '/services'
    | '/technology'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/atf'
    | '/contact'
    | '/industries'
    | '/mobile-app'
    | '/order'
    | '/services'
    | '/technology'
  id:
    | '__root__'
    | '/'
    | '/atf'
    | '/contact'
    | '/industries'
    | '/mobile-app'
    | '/order'
    | '/services'
    | '/technology'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AtfRoute: typeof AtfRoute
  ContactRoute: typeof ContactRoute
  IndustriesRoute: typeof IndustriesRoute
  MobileAppRoute: typeof MobileAppRoute
  OrderRoute: typeof OrderRoute
  ServicesRoute: typeof ServicesRoute
  TechnologyRoute: typeof TechnologyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/technology': {
      id: '/technology'
      path: '/technology'
      fullPath: '/technology'
      preLoaderRoute: typeof TechnologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order': {
      id: '/order'
      path: '/order'
      fullPath: '/order'
      preLoaderRoute: typeof OrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mobile-app': {
      id: '/mobile-app'
      path: '/mobile-app'
      fullPath: '/mobile-app'
      preLoaderRoute: typeof MobileAppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries': {
      id: '/industries'
      path: '/industries'
      fullPath: '/industries'
      preLoaderRoute: typeof IndustriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atf': {
      id: '/atf'
      path: '/atf'
      fullPath: '/atf'
      preLoaderRoute: typeof AtfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AtfRoute: AtfRoute,
  ContactRoute: ContactRoute,
  IndustriesRoute: IndustriesRoute,
  MobileAppRoute: MobileAppRoute,
  OrderRoute: OrderRoute,
  ServicesRoute: ServicesRoute,
  TechnologyRoute: TechnologyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
